QT += serialport

PORT_AUTODETECTOR_DIR = $$PWD

INCLUDEPATH += $$PORT_AUTODETECTOR_DIR

SOURCES += $$PORT_AUTODETECTOR_DIR/gps_port_autodetector.cpp

HEADERS += $$PORT_AUTODETECTOR_DIR/gps_port_autodetector.h
